Threshold By Plane Configurables
DUNE-DAQ/fddaqconf pull request #35
Opened 2024-05-07 11:36 UTC by aeoranday

Configurables PR for TPG threshold by plane implementation in [fdreadoutlibs](https://github.com/DUNE-DAQ/fdreadoutlibs/pull/177). The `<plane>_threshold` default value of 0 makes that plane's threshold the same as `tpg_threshold` during runtime.

2024-05-08 12:38 UTC, alessandrothea approved these changes

2024-05-08 12:52 UTC, alessandrothea requested changes

2024-05-08 12:52 UTC, alessandrothea commented on schema/fddaqconf/readoutgen.jsonnet
>      s.field( "tpg_threshold", types.count, default=120, doc="Select TPG threshold"),
Remove?

2024-05-08 12:52 UTC, alessandrothea commented on schema/fddaqconf/readoutgen.jsonnet
> +    s.field( "induction1_threshold", types.count, default=0, doc="Select TPG threshold for Induction 1 plane. Defaults to tpg_threshold value."),
Prefix `tpg_`

2024-05-09 09:06 UTC, aeoranday commented
Latest commit made the word choice changes to match what is used in `detchannelmaps`. Configs and variables now refer to planes 0, 1, and 2 instead of induction 1, induction 2, and collection. Also prefixed with `tpg_`.

2024-05-13 13:33 UTC, alessandrothea approved these changes

2024-05-14 16:35 UTC, merged